---
swagger: '2.0'
info:
  version: 1.0.0
  title: Statisitka hlukových senzorů
schemes:
  - http
basePath: /
paths:
  /device/{devEUI}/statistics:
    get:
      x-swagger-router-controller: "Statistics"
      parameters:
        - name: devEUI
          in: path
          description: ID čidla / zařízení.
          type: string
          required: true
        - name: date
          in: query
          description: Bude vždy den (tj. bez casu resp. k pulnoci). Pokud je parametr zadaný tak se v response vrací jen jeden interval zpětně pro každý typ statistiky.
          type: string
          required: false
      operationId: "rootGET"
      produces:
        - application/json
      responses:
        200:
          description: Vrací vypočítané statistiky pro dané datum. Vrací tyto typy statistik - HOUR, DAY6_22, DAY18_22, NIGHT22_6, DAY24, WEEK, MONTH
          schema:
            type: object
            properties:
              devEUI:
                $ref: '#/definitions/devEUI'
              statistics:
                type: array
                items:
                  $ref: '#/definitions/statistics'
definitions:
  devEUI:
    type: string
    description: ID čidla / zařízení
  statistics:
    type: object
    properties:
      type:
        type: string
        enum:
        - HOUR,
        - DAY6_22
        - DAY18_22
        - NIGHT22_6
        - DAY24
        - WEEK
        - MONTH  
        description: Typ statistiky.
      avgValues:
        type: array
        description: Samotná statistická data.
        items:
          $ref: '#/definitions/avgValues'
  avgValues:
    type: object
    properties:
      date:
        type: string
        description: Celá hodina pro kterou platí spočtený průměr.
      avgValue:
        type: string
        description: Průměrná hodnota.